In [99]:
#we use set for taken and not taken, is better than vector beacause we don't have position
import numpy as np

In [100]:
from random import random
import numpy as np
import operator
from functools import reduce
from queue import PriorityQueue
from collections import namedtuple

In [101]:
PROBLEM_SIZE=5
NUM_SETS=10
State=namedtuple("State",["taken","not_taken"])

In [102]:
#one possible set could be:
SETS=tuple(np.array([random()<.3 for _ in range(PROBLEM_SIZE)]) for _ in range(NUM_SETS))
SETS

(array([False, False, False, False,  True]),
 array([False, False, False,  True, False]),
 array([False, False, False,  True,  True]),
 array([ True, False, False,  True, False]),
 array([False, False,  True, False, False]),
 array([False, False, False, False, False]),
 array([False, False, False, False, False]),
 array([ True,  True,  True,  True, False]),
 array([False, False,  True, False, False]),
 array([False, False, False, False,  True]))

In [103]:
state=({1,3,5},{0,2,4,6,7})#in the first position there are step taken and the second are not taken position
#how can i calculate the goal state?
[SETS[i] for i in state[0]]
np.all(reduce(np.logical_or,[SETS[i] for i in state[0]]))#our taste to for understand if we are in the goal state

False

In [104]:
def goal_check(state):
    return np.all(reduce(np.logical_or, [SETS[i] for i in state.taken], np.array([False for _ in range(PROBLEM_SIZE)])))

In [105]:
def get_number_taken(state):
    tmp=np.sum(reduce(np.logical_or, [SETS[i] for i in state.taken], np.array([False for _ in range(PROBLEM_SIZE)]))==True)
    return np.sum(reduce(np.logical_or, [SETS[i] for i in state.taken], np.array([False for _ in range(PROBLEM_SIZE)]))==True)

In [106]:
assert goal_check(State(set(range(NUM_SETS)), set())), "Probelm not solvable"


In [107]:
#we need a queue that is the frontier
frontier=PriorityQueue()
#define the initial state
frontier.put(State(set(),set(range(NUM_SETS))))
current_state=frontier.get()
contatore=0
while not goal_check(current_state):
    for action in current_state[1]:
     contatore+=1
     new_state=State (current_state.taken ^ {action}, current_state.not_taken ^{action})
     frontier.put((-get_number_taken(new_state),new_state))
    #print(current_state)
    _,current_state=frontier.get()

State(taken={0}, not_taken={1, 2, 3, 4, 5, 6, 7, 8, 9})
State(taken={2}, not_taken={0, 1, 3, 4, 5, 6, 7, 8, 9})
State(taken={6}, not_taken={0, 1, 2, 3, 4, 5, 7, 8, 9})
State(taken={9}, not_taken={0, 1, 2, 3, 4, 5, 6, 7, 8})
State(taken={5}, not_taken={0, 1, 2, 3, 4, 6, 7, 8, 9})
State(taken={1}, not_taken={0, 2, 3, 4, 5, 6, 7, 8, 9})
State(taken={4}, not_taken={0, 1, 2, 3, 5, 6, 7, 8, 9})
State(taken={3}, not_taken={0, 1, 2, 4, 5, 6, 7, 8, 9})
State(taken={8}, not_taken={0, 1, 2, 3, 4, 5, 6, 7, 9})
State(taken={7}, not_taken={0, 1, 2, 3, 4, 5, 6, 8, 9})
State(taken={0, 6}, not_taken={1, 2, 3, 4, 5, 7, 8, 9})
State(taken={0, 9}, not_taken={1, 2, 3, 4, 5, 6, 7, 8})
State(taken={5, 6}, not_taken={0, 1, 2, 3, 4, 7, 8, 9})
State(taken={9, 6}, not_taken={0, 1, 2, 3, 4, 5, 7, 8})
State(taken={4, 6}, not_taken={0, 1, 2, 3, 5, 7, 8, 9})
State(taken={8, 9}, not_taken={0, 1, 2, 3, 4, 5, 6, 7})
State(taken={9, 7}, not_taken={0, 1, 2, 3, 4, 5, 6, 8})


In [108]:
print(contatore)
current_state

148


State(taken={9, 7}, not_taken={0, 1, 2, 3, 4, 5, 6, 8})