In [11]:
#we use set for taken and not taken, is better than vector beacause we don't have position
import numpy as np

In [12]:
from random import random
import numpy as np
import operator
from functools import reduce
from queue import PriorityQueue
from collections import namedtuple

In [13]:
PROBLEM_SIZE=5
NUM_SETS=10
State=namedtuple("State",["taken","not_taken"])

In [14]:
#one possible set could be:
SETS=tuple(np.array([random()<.3 for _ in range(PROBLEM_SIZE)]) for _ in range(NUM_SETS))
SETS

(array([ True, False, False,  True, False]),
 array([ True, False, False, False,  True]),
 array([ True, False,  True, False, False]),
 array([False,  True, False, False,  True]),
 array([False, False, False, False, False]),
 array([False,  True,  True, False, False]),
 array([False, False, False,  True,  True]),
 array([False, False,  True, False,  True]),
 array([False, False, False,  True,  True]),
 array([ True,  True, False,  True, False]))

In [15]:
state=({1,3,5},{0,2,4,6,7})#in the first position there are step taken and the second are not taken position
#how can i calculate the goal state?
[SETS[i] for i in state[0]]
np.all(reduce(np.logical_or,[SETS[i] for i in state[0]]))#our taste to for understand if we are in the goal state

False

In [16]:
def goal_check(state):
    return np.all(reduce(np.logical_or, [SETS[i] for i in state.taken], np.array([False for _ in range(PROBLEM_SIZE)])))

In [17]:
def get_number_taken(state):
    tmp=np.sum(reduce(np.logical_or, [SETS[i] for i in state.taken], np.array([False for _ in range(PROBLEM_SIZE)]))==True)
    return np.sum(reduce(np.logical_or, [SETS[i] for i in state.taken], np.array([False for _ in range(PROBLEM_SIZE)]))==True)

In [18]:
assert goal_check(State(set(range(NUM_SETS)), set())), "Probelm not solvable"


In [19]:
#we need a queue that is the frontier
frontier=PriorityQueue()
#define the initial state
frontier.put(State(set(),set(range(NUM_SETS))))
current_state=frontier.get()
contatore=0
while not goal_check(current_state):
    for action in current_state[1]:
     contatore+=1
     new_state=State (current_state.taken ^ {action}, current_state.not_taken ^{action})
     frontier.put((-get_number_taken(new_state),new_state))
    #print(current_state)
    _,current_state=frontier.get()

In [20]:
frontier_=PriorityQueue()
#define the initial state
frontier_.put(State(set(),set(range(NUM_SETS))))
current_state_=frontier_.get()
contatore_=0
while not goal_check(current_state_):
    for action in current_state_[1]:
     contatore_+=1
     new_state=State (current_state_.taken ^ {action}, current_state_.not_taken ^{action})
     frontier_.put((-len(current_state_),new_state))
    #print(current_state)
    _,current_state_=frontier_.get()

In [21]:
print("First method",contatore,current_state)
print("Method with Dijkstra",contatore_, current_state_)

current_state

First method 19 State(taken={9, 7}, not_taken={0, 1, 2, 3, 4, 5, 6, 8})
First method 19


State(taken={9, 7}, not_taken={0, 1, 2, 3, 4, 5, 6, 8})