In [41]:
#we use set for taken and not taken, is better than vector beacause we don't have position
import numpy as np

In [42]:
from random import random
import numpy as np
import operator
from functools import reduce
from queue import PriorityQueue
from collections import namedtuple

In [43]:
PROBLEM_SIZE=5
NUM_SETS=10
State=namedtuple("State",["taken","not_taken"])

In [44]:
#one possible set could be:
SETS=tuple(np.array([random()<.3 for _ in range(PROBLEM_SIZE)]) for _ in range(NUM_SETS))
SETS

(array([False,  True, False, False, False]),
 array([False, False, False, False,  True]),
 array([False,  True,  True, False, False]),
 array([ True, False, False, False, False]),
 array([False,  True, False,  True, False]),
 array([False,  True, False, False, False]),
 array([ True, False, False, False,  True]),
 array([ True,  True, False,  True, False]),
 array([False,  True, False, False, False]),
 array([ True,  True, False, False,  True]))

In [45]:
state=({1,3,5},{0,2,4,6,7})#in the first position there are step taken and the second are not taken position
#how can i calculate the goal state?
[SETS[i] for i in state[0]]
np.all(reduce(np.logical_or,[SETS[i] for i in state[0]]))#our taste to for understand if we are in the goal state

False

In [46]:
def goal_check(state):
    return np.all(reduce(np.logical_or, [SETS[i] for i in state.taken], np.array([False for _ in range(PROBLEM_SIZE)])))

In [47]:
assert goal_check(State(set(range(NUM_SETS)), set())), "Probelm not solvable"


In [48]:
frontier_=PriorityQueue()
#define the initial state
frontier_.put(State(set(),set(range(NUM_SETS))))
current_state_=frontier_.get()
contatore_=0
while not goal_check(current_state_):
    for action in current_state_[1]:
     contatore_+=1
     new_state=State (current_state_.taken ^ {action}, current_state_.not_taken ^{action})
     frontier_.put((len(current_state_.taken),new_state))
    _,current_state_=frontier_.get()

In [49]:
print("Method with Dijkstra use",contatore_,"steps and give us: ", current_state_)


Method with Dijkstra use 862 steps and give us:  State(taken={9, 2, 7}, not_taken={0, 1, 3, 4, 5, 6, 8})
